// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1) {
  return window['go']['main']['DataGeneratorService']['Generate'](arg1);
}

export function GetPresets() {
  return window['go']['main']['DataGeneratorService']['GetPresets']();
}

export function ValidateTemplate(arg1) {
  return window['go']['main']['DataGeneratorService']['ValidateTemplate'](arg1);
}
