// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jwt} from '../models';

export function Decode(arg1:string):Promise<jwt.DecodeResponse>;

export function Encode(arg1:string,arg2:string,arg3:string,arg4:string):Promise<jwt.EncodeResponse>;

export function Verify(arg1:string,arg2:string,arg3:string):Promise<jwt.VerifyResponse>;
