// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from '@wailsio/runtime';

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "app:quit": string;
            "command-palette:open": string;
            "settings:changed": { [_ in string]?: any };
            "spotlight:close": string;
            "spotlight:closed": string;
            "spotlight:command-selected": string;
            "time": string;
            "window:toggle": string;
        }
    }
}