// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateBarcode(arg1) {
  return window['go']['wails']['BarcodeService']['GenerateBarcode'](arg1);
}

export function GetBarcodeSizes() {
  return window['go']['wails']['BarcodeService']['GetBarcodeSizes']();
}

export function GetBarcodeStandards() {
  return window['go']['wails']['BarcodeService']['GetBarcodeStandards']();
}

export function GetQRErrorLevels() {
  return window['go']['wails']['BarcodeService']['GetQRErrorLevels']();
}

export function Startup(arg1) {
  return window['go']['wails']['BarcodeService']['Startup'](arg1);
}

export function ValidateContent(arg1, arg2) {
  return window['go']['wails']['BarcodeService']['ValidateContent'](arg1, arg2);
}
