// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';
import {context} from '../models';

export function GenerateBarcode(arg1:wails.GenerateBarcodeRequest):Promise<wails.GenerateBarcodeResponse>;

export function GetBarcodeSizes():Promise<Array<Record<string, any>>>;

export function GetBarcodeStandards():Promise<Array<Record<string, string>>>;

export function GetQRErrorLevels():Promise<Array<Record<string, string>>>;

export function Startup(arg1:context.Context):Promise<void>;

export function ValidateContent(arg1:string,arg2:string):Promise<Record<string, any>>;
