// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Format(arg1) {
  return window['go']['wails']['CodeFormatterService']['Format'](arg1);
}

export function Startup(arg1) {
  return window['go']['wails']['CodeFormatterService']['Startup'](arg1);
}
