// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {codeformatter} from '../models';
import {context} from '../models';

export function Format(arg1:codeformatter.FormatRequest):Promise<codeformatter.FormatResponse>;

export function Startup(arg1:context.Context):Promise<void>;
