// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['ConversionService']['Convert'](arg1, arg2, arg3, arg4);
}

export function Startup(arg1) {
  return window['go']['wails']['ConversionService']['Startup'](arg1);
}
