// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Convert(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
