// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {datagenerator} from '../models';
import {context} from '../models';

export function Generate(arg1:datagenerator.GenerateRequest):Promise<datagenerator.GenerateResponse>;

export function GetPresets():Promise<datagenerator.PresetsResponse>;

export function Startup(arg1:context.Context):Promise<void>;

export function ValidateTemplate(arg1:string):Promise<datagenerator.ValidationResult>;
