// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decode(arg1) {
  return window['go']['wails']['JWTService']['Decode'](arg1);
}

export function Encode(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['JWTService']['Encode'](arg1, arg2, arg3, arg4);
}

export function Startup(arg1) {
  return window['go']['wails']['JWTService']['Startup'](arg1);
}

export function Verify(arg1, arg2, arg3) {
  return window['go']['wails']['JWTService']['Verify'](arg1, arg2, arg3);
}
