export const THEMES = {
  'github-dark': {
    name: 'GitHub Dark',
    type: 'dark',
    isBuiltIn: true,
    colors: {
      background: 'var(--gray-1)',
      foreground: 'var(--gray-12)',
      card: 'var(--gray-2)',
      'card-foreground': 'var(--gray-12)',
      popover: 'var(--gray-2)',
      'popover-foreground': 'var(--gray-12)',
      primary: 'var(--blue-9)',
      'primary-foreground': 'white',
      secondary: 'var(--gray-3)',
      'secondary-foreground': 'var(--gray-12)',
      muted: 'var(--gray-3)',
      'muted-foreground': 'var(--gray-11)',
      accent: 'var(--gray-4)',
      'accent-foreground': 'var(--gray-12)',
      destructive: 'var(--red-9)',
      'destructive-foreground': 'white',
      border: 'var(--gray-6)',
      input: 'var(--gray-3)',
      ring: 'var(--blue-9)',
      success: 'var(--green-9)',
      warning: '#e5c07b',
      'sidebar-background': 'var(--gray-2)',
      'sidebar-foreground': 'var(--gray-12)',
      'sidebar-accent': 'var(--blue-9)',
      'titlebar-background': 'var(--gray-2)',
      'scrollbar-thumb': 'var(--gray-7)',
      'scrollbar-track': 'transparent',
    },
    tokenColors: [
      { scope: 'keyword', color: '#d73a49' },
      { scope: 'string', color: '#032f62' },
      { scope: 'number', color: '#005cc5' },
      { scope: 'comment', color: '#6a737d' },
      { scope: 'type', color: '#6f42c1' },
      { scope: 'function', color: '#6f42c1' },
      { scope: 'variable', color: '#e36209' },
      { scope: 'operator', color: '#d73a49' },
      { scope: 'punctuation', color: '#24292e' },
      { scope: 'tag', color: '#22863a' },
      { scope: 'attribute', color: '#6f42c1' },
      { scope: 'property', color: '#005cc5' },
      { scope: 'constant', color: '#005cc5' },
      { scope: 'bool', color: '#005cc5' },
      { scope: 'null', color: '#005cc5' },
      { scope: 'class', color: '#6f42c1' },
      { scope: 'definition', color: '#6f42c1' },
    ],
  },
  'github-light': {
    name: 'GitHub Light',
    type: 'light',
    isBuiltIn: true,
    colors: {
      background: 'var(--gray-1)',
      foreground: 'var(--gray-12)',
      card: 'var(--gray-2)',
      'card-foreground': 'var(--gray-12)',
      popover: 'var(--gray-2)',
      'popover-foreground': 'var(--gray-12)',
      primary: 'var(--blue-9)',
      'primary-foreground': 'white',
      secondary: 'var(--gray-3)',
      'secondary-foreground': 'var(--gray-12)',
      muted: 'var(--gray-3)',
      'muted-foreground': 'var(--gray-11)',
      accent: 'var(--gray-4)',
      'accent-foreground': 'var(--gray-12)',
      destructive: 'var(--red-9)',
      'destructive-foreground': 'white',
      border: 'var(--gray-6)',
      input: 'var(--gray-3)',
      ring: 'var(--blue-9)',
      success: 'var(--green-9)',
      warning: '#e5c07b',
      'sidebar-background': 'var(--gray-2)',
      'sidebar-foreground': 'var(--gray-12)',
      'sidebar-accent': 'var(--blue-9)',
      'titlebar-background': 'var(--gray-2)',
      'scrollbar-thumb': 'var(--gray-7)',
      'scrollbar-track': 'transparent',
    },
    tokenColors: [
      { scope: 'keyword', color: '#d73a49' },
      { scope: 'string', color: '#032f62' },
      { scope: 'number', color: '#005cc5' },
      { scope: 'comment', color: '#6a737d' },
      { scope: 'type', color: '#6f42c1' },
      { scope: 'function', color: '#6f42c1' },
      { scope: 'variable', color: '#e36209' },
      { scope: 'operator', color: '#d73a49' },
      { scope: 'punctuation', color: '#24292e' },
      { scope: 'tag', color: '#22863a' },
      { scope: 'attribute', color: '#6f42c1' },
      { scope: 'property', color: '#005cc5' },
      { scope: 'constant', color: '#005cc5' },
      { scope: 'bool', color: '#005cc5' },
      { scope: 'null', color: '#005cc5' },
      { scope: 'class', color: '#6f42c1' },
      { scope: 'definition', color: '#6f42c1' },
    ],
  },
};
