export default {
  name: 'Catppuccin Mocha',
  type: 'dark',
  isBuiltIn: false,
  colors: {
    background: '#1e1e2e',
    foreground: '#cdd6f4',
    card: '#181825',
    'card-foreground': '#cdd6f4',
    popover: '#181825',
    'popover-foreground': '#cdd6f4',
    primary: '#cba6f7',
    'primary-foreground': '#11111b',
    secondary: '#313244',
    'secondary-foreground': '#cdd6f4',
    muted: '#313244',
    'muted-foreground': '#a6adc8',
    accent: '#f5c2e7',
    'accent-foreground': '#11111b',
    destructive: '#f38ba8',
    'destructive-foreground': '#ffffff',
    border: '#45475a',
    input: '#313244',
    ring: '#cba6f7',
    success: '#a6e3a1',
    'success-foreground': '#11111b',
    warning: '#f9e2af',
    'warning-foreground': '#11111b',
    'sidebar-background': '#181825',
    'sidebar-foreground': '#cdd6f4',
    'sidebar-accent': '#cba6f7',
    'titlebar-background': '#181825',
    'scrollbar-thumb': '#45475a',
    'scrollbar-track': '#181825',
  },
  tokenColors: [
    { scope: 'keyword',       color: '#cba6f7' },
    { scope: 'string',        color: '#a6e3a1' },
    { scope: 'number',        color: '#fab387' },
    { scope: 'comment',       color: '#6c7086' },
    { scope: 'type',          color: '#89b4fa' },
    { scope: 'function',      color: '#89b4fa' },
    { scope: 'variable',      color: '#f5c2e7' },
    { scope: 'operator',      color: '#89dceb' },
    { scope: 'punctuation',   color: '#cdd6f4' },
    { scope: 'tag',           color: '#f38ba8' },
    { scope: 'attribute',     color: '#fab387' },
    { scope: 'property',      color: '#89b4fa' },
    { scope: 'constant',      color: '#fab387' },
    { scope: 'bool',          color: '#fab387' },
    { scope: 'null',          color: '#fab387' },
    { scope: 'class',         color: '#89b4fa' },
    { scope: 'definition',    color: '#89b4fa' },
  ],
};
