export default {
  name: 'Dracula',
  type: 'dark',
  isBuiltIn: false,
  colors: {
    background: '#282a36',
    foreground: '#f8f8f2',
    card: '#21222c',
    'card-foreground': '#f8f8f2',
    popover: '#21222c',
    'popover-foreground': '#f8f8f2',
    primary: '#bd93f9',
    'primary-foreground': '#ffffff',
    secondary: '#44475a',
    'secondary-foreground': '#f8f8f2',
    muted: '#44475a',
    'muted-foreground': '#6272a4',
    accent: '#ff79c6',
    'accent-foreground': '#ffffff',
    destructive: '#ff5555',
    'destructive-foreground': '#ffffff',
    border: '#44475a',
    input: '#44475a',
    ring: '#bd93f9',
    success: '#50fa7b',
    'success-foreground': '#ffffff',
    warning: '#f1fa8c',
    'warning-foreground': '#282a36',
    'sidebar-background': '#21222c',
    'sidebar-foreground': '#f8f8f2',
    'sidebar-accent': '#bd93f9',
    'titlebar-background': '#21222c',
    'scrollbar-thumb': '#44475a',
    'scrollbar-track': '#21222c',
  },
  tokenColors: [
    { scope: 'keyword',       color: '#ff79c6' },
    { scope: 'string',        color: '#f1fa8c' },
    { scope: 'number',        color: '#bd93f9' },
    { scope: 'comment',       color: '#6272a4' },
    { scope: 'type',          color: '#8be9fd' },
    { scope: 'function',      color: '#50fa7b' },
    { scope: 'variable',      color: '#f8f8f2' },
    { scope: 'operator',      color: '#ff79c6' },
    { scope: 'punctuation',   color: '#f8f8f2' },
    { scope: 'tag',           color: '#ff79c6' },
    { scope: 'attribute',     color: '#50fa7b' },
    { scope: 'property',      color: '#66d9ef' },
    { scope: 'constant',      color: '#bd93f9' },
    { scope: 'bool',          color: '#bd93f9' },
    { scope: 'null',          color: '#bd93f9' },
    { scope: 'class',         color: '#8be9fd' },
    { scope: 'definition',    color: '#50fa7b' },
  ],
};
