export default {
  name: 'Nord',
  type: 'dark',
  isBuiltIn: false,
  colors: {
    background: '#2e3440',
    foreground: '#d8dee9',
    card: '#3b4252',
    'card-foreground': '#d8dee9',
    popover: '#3b4252',
    'popover-foreground': '#d8dee9',
    primary: '#88c0d0',
    'primary-foreground': '#2e3440',
    secondary: '#434c5e',
    'secondary-foreground': '#d8dee9',
    muted: '#434c5e',
    'muted-foreground': '#81a1c1',
    accent: '#88c0d0',
    'accent-foreground': '#2e3440',
    destructive: '#bf616a',
    'destructive-foreground': '#ffffff',
    border: '#4c566a',
    input: '#434c5e',
    ring: '#88c0d0',
    success: '#a3be8c',
    'success-foreground': '#2e3440',
    warning: '#ebcb8b',
    'warning-foreground': '#2e3440',
    'sidebar-background': '#3b4252',
    'sidebar-foreground': '#d8dee9',
    'sidebar-accent': '#88c0d0',
    'titlebar-background': '#3b4252',
    'scrollbar-thumb': '#4c566a',
    'scrollbar-track': '#3b4252',
  },
  tokenColors: [
    { scope: 'keyword',       color: '#81a1c1' },
    { scope: 'string',        color: '#a3be8c' },
    { scope: 'number',        color: '#b48ead' },
    { scope: 'comment',       color: '#616e88' },
    { scope: 'type',          color: '#8fbcbb' },
    { scope: 'function',      color: '#88c0d0' },
    { scope: 'variable',      color: '#d8dee9' },
    { scope: 'operator',      color: '#81a1c1' },
    { scope: 'punctuation',   color: '#d8dee9' },
    { scope: 'tag',           color: '#81a1c1' },
    { scope: 'attribute',     color: '#8fbcbb' },
    { scope: 'property',      color: '#88c0d0' },
    { scope: 'constant',      color: '#b48ead' },
    { scope: 'bool',          color: '#b48ead' },
    { scope: 'null',          color: '#b48ead' },
    { scope: 'class',         color: '#8fbcbb' },
    { scope: 'definition',    color: '#88c0d0' },
  ],
};
