export default {
  name: 'Solarized Light',
  type: 'light',
  isBuiltIn: false,
  colors: {
    background: '#fdf6e3',
    foreground: '#657b83',
    card: '#eee8d5',
    'card-foreground': '#657b83',
    popover: '#eee8d5',
    'popover-foreground': '#657b83',
    primary: '#268bd2',
    'primary-foreground': '#ffffff',
    secondary: '#93a1a1',
    'secondary-foreground': '#657b83',
    muted: '#93a1a1',
    'muted-foreground': '#839496',
    accent: '#2aa198',
    'accent-foreground': '#ffffff',
    destructive: '#dc322f',
    'destructive-foreground': '#ffffff',
    border: '#d5c4a1',
    input: '#eee8d5',
    ring: '#268bd2',
    success: '#859900',
    'success-foreground': '#ffffff',
    warning: '#b58900',
    'warning-foreground': '#fdf6e3',
    'sidebar-background': '#eee8d5',
    'sidebar-foreground': '#657b83',
    'sidebar-accent': '#268bd2',
    'titlebar-background': '#eee8d5',
    'scrollbar-thumb': '#93a1a1',
    'scrollbar-track': '#eee8d5',
  },
  tokenColors: [
    { scope: 'keyword',       color: '#859900' },
    { scope: 'string',        color: '#2aa198' },
    { scope: 'number',        color: '#d33682' },
    { scope: 'comment',       color: '#93a1a1' },
    { scope: 'type',          color: '#b58900' },
    { scope: 'function',      color: '#268bd2' },
    { scope: 'variable',      color: '#b58900' },
    { scope: 'operator',      color: '#859900' },
    { scope: 'punctuation',   color: '#657b83' },
    { scope: 'tag',           color: '#268bd2' },
    { scope: 'attribute',     color: '#b58900' },
    { scope: 'property',      color: '#268bd2' },
    { scope: 'constant',      color: '#d33682' },
    { scope: 'bool',          color: '#d33682' },
    { scope: 'null',          color: '#d33682' },
    { scope: 'class',         color: '#b58900' },
    { scope: 'definition',    color: '#268bd2' },
  ],
};
